package com.genpact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QbPortletField service. Represents a row in the &quot;t_qb_portlet_field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.genpact.model.impl.QbPortletFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.genpact.model.impl.QbPortletFieldImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbPortletField
 * @see com.genpact.model.impl.QbPortletFieldImpl
 * @see com.genpact.model.impl.QbPortletFieldModelImpl
 * @generated
 */
public interface QbPortletFieldModel extends BaseModel<QbPortletField> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a qb portlet field model instance should use the {@link QbPortletField} interface instead.
     */

    /**
     * Returns the primary key of this qb portlet field.
     *
     * @return the primary key of this qb portlet field
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this qb portlet field.
     *
     * @param primaryKey the primary key of this qb portlet field
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the field_id of this qb portlet field.
     *
     * @return the field_id of this qb portlet field
     */
    public long getField_id();

    /**
     * Sets the field_id of this qb portlet field.
     *
     * @param field_id the field_id of this qb portlet field
     */
    public void setField_id(long field_id);

    /**
     * Returns the field_name of this qb portlet field.
     *
     * @return the field_name of this qb portlet field
     */
    @AutoEscape
    public String getField_name();

    /**
     * Sets the field_name of this qb portlet field.
     *
     * @param field_name the field_name of this qb portlet field
     */
    public void setField_name(String field_name);

    /**
     * Returns the field_label_name of this qb portlet field.
     *
     * @return the field_label_name of this qb portlet field
     */
    @AutoEscape
    public String getField_label_name();

    /**
     * Sets the field_label_name of this qb portlet field.
     *
     * @param field_label_name the field_label_name of this qb portlet field
     */
    public void setField_label_name(String field_label_name);

    /**
     * Returns the portlet_id of this qb portlet field.
     *
     * @return the portlet_id of this qb portlet field
     */
    public long getPortlet_id();

    /**
     * Sets the portlet_id of this qb portlet field.
     *
     * @param portlet_id the portlet_id of this qb portlet field
     */
    public void setPortlet_id(long portlet_id);

    /**
     * Returns the reference_portlet_id of this qb portlet field.
     *
     * @return the reference_portlet_id of this qb portlet field
     */
    public long getReference_portlet_id();

    /**
     * Sets the reference_portlet_id of this qb portlet field.
     *
     * @param reference_portlet_id the reference_portlet_id of this qb portlet field
     */
    public void setReference_portlet_id(long reference_portlet_id);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(QbPortletField qbPortletField);

    @Override
    public int hashCode();

    @Override
    public CacheModel<QbPortletField> toCacheModel();

    @Override
    public QbPortletField toEscapedModel();

    @Override
    public QbPortletField toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
