package com.genpact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the QbProject service. Represents a row in the &quot;t_qb_project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.genpact.model.impl.QbProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.genpact.model.impl.QbProjectImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbProject
 * @see com.genpact.model.impl.QbProjectImpl
 * @see com.genpact.model.impl.QbProjectModelImpl
 * @generated
 */
public interface QbProjectModel extends BaseModel<QbProject> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a qb project model instance should use the {@link QbProject} interface instead.
     */

    /**
     * Returns the primary key of this qb project.
     *
     * @return the primary key of this qb project
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this qb project.
     *
     * @param primaryKey the primary key of this qb project
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the project_id of this qb project.
     *
     * @return the project_id of this qb project
     */
    public long getProject_id();

    /**
     * Sets the project_id of this qb project.
     *
     * @param project_id the project_id of this qb project
     */
    public void setProject_id(long project_id);

    /**
     * Returns the project_name of this qb project.
     *
     * @return the project_name of this qb project
     */
    @AutoEscape
    public String getProject_name();

    /**
     * Sets the project_name of this qb project.
     *
     * @param project_name the project_name of this qb project
     */
    public void setProject_name(String project_name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(QbProject qbProject);

    @Override
    public int hashCode();

    @Override
    public CacheModel<QbProject> toCacheModel();

    @Override
    public QbProject toEscapedModel();

    @Override
    public QbProject toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
