package com.genpact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TalendProcess service. Represents a row in the &quot;talend_TalendProcess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.genpact.model.impl.TalendProcessModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.genpact.model.impl.TalendProcessImpl}.
 * </p>
 *
 * @author 710008328
 * @see TalendProcess
 * @see com.genpact.model.impl.TalendProcessImpl
 * @see com.genpact.model.impl.TalendProcessModelImpl
 * @generated
 */
public interface TalendProcessModel extends BaseModel<TalendProcess> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a talend process model instance should use the {@link TalendProcess} interface instead.
     */

    /**
     * Returns the primary key of this talend process.
     *
     * @return the primary key of this talend process
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this talend process.
     *
     * @param primaryKey the primary key of this talend process
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the process ID of this talend process.
     *
     * @return the process ID of this talend process
     */
    public long getProcessId();

    /**
     * Sets the process ID of this talend process.
     *
     * @param processId the process ID of this talend process
     */
    public void setProcessId(long processId);

    /**
     * Returns the create date of this talend process.
     *
     * @return the create date of this talend process
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this talend process.
     *
     * @param createDate the create date of this talend process
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this talend process.
     *
     * @return the modified date of this talend process
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this talend process.
     *
     * @param modifiedDate the modified date of this talend process
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this talend process.
     *
     * @return the name of this talend process
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this talend process.
     *
     * @param name the name of this talend process
     */
    public void setName(String name);

    /**
     * Returns the version of this talend process.
     *
     * @return the version of this talend process
     */
    @AutoEscape
    public String getVersion();

    /**
     * Sets the version of this talend process.
     *
     * @param version the version of this talend process
     */
    public void setVersion(String version);

    /**
     * Returns the class name of this talend process.
     *
     * @return the class name of this talend process
     */
    @AutoEscape
    public String getClassName();

    /**
     * Sets the class name of this talend process.
     *
     * @param className the class name of this talend process
     */
    public void setClassName(String className);

    /**
     * Returns the file entry ID of this talend process.
     *
     * @return the file entry ID of this talend process
     */
    public long getFileEntryId();

    /**
     * Sets the file entry ID of this talend process.
     *
     * @param fileEntryId the file entry ID of this talend process
     */
    public void setFileEntryId(long fileEntryId);

    /**
     * Returns the description of this talend process.
     *
     * @return the description of this talend process
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this talend process.
     *
     * @param description the description of this talend process
     */
    public void setDescription(String description);

    /**
     * Returns the context of this talend process.
     *
     * @return the context of this talend process
     */
    @AutoEscape
    public String getContext();

    /**
     * Sets the context of this talend process.
     *
     * @param context the context of this talend process
     */
    public void setContext(String context);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(TalendProcess talendProcess);

    @Override
    public int hashCode();

    @Override
    public CacheModel<TalendProcess> toCacheModel();

    @Override
    public TalendProcess toEscapedModel();

    @Override
    public TalendProcess toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
