package com.genpact.model.impl;

import com.genpact.model.QbPortletField;

import com.genpact.service.QbPortletFieldLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the QbPortletField service. Represents a row in the &quot;t_qb_portlet_field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QbPortletFieldImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbPortletFieldImpl
 * @see com.genpact.model.QbPortletField
 * @generated
 */
public abstract class QbPortletFieldBaseImpl extends QbPortletFieldModelImpl
    implements QbPortletField {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a qb portlet field model instance should use the {@link QbPortletField} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            QbPortletFieldLocalServiceUtil.addQbPortletField(this);
        } else {
            QbPortletFieldLocalServiceUtil.updateQbPortletField(this);
        }
    }
}
