package com.genpact.model.impl;

import com.genpact.model.QbPortlet;

import com.genpact.service.QbPortletLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the QbPortlet service. Represents a row in the &quot;t_qb_portlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QbPortletImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbPortletImpl
 * @see com.genpact.model.QbPortlet
 * @generated
 */
public abstract class QbPortletBaseImpl extends QbPortletModelImpl
    implements QbPortlet {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a qb portlet model instance should use the {@link QbPortlet} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            QbPortletLocalServiceUtil.addQbPortlet(this);
        } else {
            QbPortletLocalServiceUtil.updateQbPortlet(this);
        }
    }
}
