package com.genpact.model.impl;

import com.genpact.model.QbPortletField;
import com.genpact.model.QbPortletFieldModel;
import com.genpact.model.QbPortletFieldSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the QbPortletField service. Represents a row in the &quot;t_qb_portlet_field&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.genpact.model.QbPortletFieldModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QbPortletFieldImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbPortletFieldImpl
 * @see com.genpact.model.QbPortletField
 * @see com.genpact.model.QbPortletFieldModel
 * @generated
 */
@JSON(strict = true)
public class QbPortletFieldModelImpl extends BaseModelImpl<QbPortletField>
    implements QbPortletFieldModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a qb portlet field model instance should use the {@link com.genpact.model.QbPortletField} interface instead.
     */
    public static final String TABLE_NAME = "t_qb_portlet_field";
    public static final Object[][] TABLE_COLUMNS = {
            { "field_id", Types.BIGINT },
            { "field_name", Types.VARCHAR },
            { "field_label_name", Types.VARCHAR },
            { "portlet_id", Types.BIGINT },
            { "reference_portlet_id", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table t_qb_portlet_field (field_id LONG not null primary key,field_name VARCHAR(75) null,field_label_name VARCHAR(75) null,portlet_id LONG,reference_portlet_id LONG)";
    public static final String TABLE_SQL_DROP = "drop table t_qb_portlet_field";
    public static final String ORDER_BY_JPQL = " ORDER BY qbPortletField.field_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY t_qb_portlet_field.field_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.genpact.model.QbPortletField"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.genpact.model.QbPortletField"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.genpact.model.QbPortletField"));
    private static ClassLoader _classLoader = QbPortletField.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            QbPortletField.class
        };
    private long _field_id;
    private String _field_name;
    private String _field_label_name;
    private long _portlet_id;
    private long _reference_portlet_id;
    private QbPortletField _escapedModel;

    public QbPortletFieldModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static QbPortletField toModel(QbPortletFieldSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        QbPortletField model = new QbPortletFieldImpl();

        model.setField_id(soapModel.getField_id());
        model.setField_name(soapModel.getField_name());
        model.setField_label_name(soapModel.getField_label_name());
        model.setPortlet_id(soapModel.getPortlet_id());
        model.setReference_portlet_id(soapModel.getReference_portlet_id());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<QbPortletField> toModels(QbPortletFieldSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<QbPortletField> models = new ArrayList<QbPortletField>(soapModels.length);

        for (QbPortletFieldSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _field_id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setField_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _field_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return QbPortletField.class;
    }

    @Override
    public String getModelClassName() {
        return QbPortletField.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("field_id", getField_id());
        attributes.put("field_name", getField_name());
        attributes.put("field_label_name", getField_label_name());
        attributes.put("portlet_id", getPortlet_id());
        attributes.put("reference_portlet_id", getReference_portlet_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long field_id = (Long) attributes.get("field_id");

        if (field_id != null) {
            setField_id(field_id);
        }

        String field_name = (String) attributes.get("field_name");

        if (field_name != null) {
            setField_name(field_name);
        }

        String field_label_name = (String) attributes.get("field_label_name");

        if (field_label_name != null) {
            setField_label_name(field_label_name);
        }

        Long portlet_id = (Long) attributes.get("portlet_id");

        if (portlet_id != null) {
            setPortlet_id(portlet_id);
        }

        Long reference_portlet_id = (Long) attributes.get(
                "reference_portlet_id");

        if (reference_portlet_id != null) {
            setReference_portlet_id(reference_portlet_id);
        }
    }

    @JSON
    @Override
    public long getField_id() {
        return _field_id;
    }

    @Override
    public void setField_id(long field_id) {
        _field_id = field_id;
    }

    @JSON
    @Override
    public String getField_name() {
        if (_field_name == null) {
            return StringPool.BLANK;
        } else {
            return _field_name;
        }
    }

    @Override
    public void setField_name(String field_name) {
        _field_name = field_name;
    }

    @JSON
    @Override
    public String getField_label_name() {
        if (_field_label_name == null) {
            return StringPool.BLANK;
        } else {
            return _field_label_name;
        }
    }

    @Override
    public void setField_label_name(String field_label_name) {
        _field_label_name = field_label_name;
    }

    @JSON
    @Override
    public long getPortlet_id() {
        return _portlet_id;
    }

    @Override
    public void setPortlet_id(long portlet_id) {
        _portlet_id = portlet_id;
    }

    @JSON
    @Override
    public long getReference_portlet_id() {
        return _reference_portlet_id;
    }

    @Override
    public void setReference_portlet_id(long reference_portlet_id) {
        _reference_portlet_id = reference_portlet_id;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            QbPortletField.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public QbPortletField toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (QbPortletField) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        QbPortletFieldImpl qbPortletFieldImpl = new QbPortletFieldImpl();

        qbPortletFieldImpl.setField_id(getField_id());
        qbPortletFieldImpl.setField_name(getField_name());
        qbPortletFieldImpl.setField_label_name(getField_label_name());
        qbPortletFieldImpl.setPortlet_id(getPortlet_id());
        qbPortletFieldImpl.setReference_portlet_id(getReference_portlet_id());

        qbPortletFieldImpl.resetOriginalValues();

        return qbPortletFieldImpl;
    }

    @Override
    public int compareTo(QbPortletField qbPortletField) {
        long primaryKey = qbPortletField.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof QbPortletField)) {
            return false;
        }

        QbPortletField qbPortletField = (QbPortletField) obj;

        long primaryKey = qbPortletField.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<QbPortletField> toCacheModel() {
        QbPortletFieldCacheModel qbPortletFieldCacheModel = new QbPortletFieldCacheModel();

        qbPortletFieldCacheModel.field_id = getField_id();

        qbPortletFieldCacheModel.field_name = getField_name();

        String field_name = qbPortletFieldCacheModel.field_name;

        if ((field_name != null) && (field_name.length() == 0)) {
            qbPortletFieldCacheModel.field_name = null;
        }

        qbPortletFieldCacheModel.field_label_name = getField_label_name();

        String field_label_name = qbPortletFieldCacheModel.field_label_name;

        if ((field_label_name != null) && (field_label_name.length() == 0)) {
            qbPortletFieldCacheModel.field_label_name = null;
        }

        qbPortletFieldCacheModel.portlet_id = getPortlet_id();

        qbPortletFieldCacheModel.reference_portlet_id = getReference_portlet_id();

        return qbPortletFieldCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{field_id=");
        sb.append(getField_id());
        sb.append(", field_name=");
        sb.append(getField_name());
        sb.append(", field_label_name=");
        sb.append(getField_label_name());
        sb.append(", portlet_id=");
        sb.append(getPortlet_id());
        sb.append(", reference_portlet_id=");
        sb.append(getReference_portlet_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("com.genpact.model.QbPortletField");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>field_id</column-name><column-value><![CDATA[");
        sb.append(getField_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>field_name</column-name><column-value><![CDATA[");
        sb.append(getField_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>field_label_name</column-name><column-value><![CDATA[");
        sb.append(getField_label_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>portlet_id</column-name><column-value><![CDATA[");
        sb.append(getPortlet_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>reference_portlet_id</column-name><column-value><![CDATA[");
        sb.append(getReference_portlet_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
