package com.genpact.model.impl;

import com.genpact.model.QbProject;

import com.genpact.service.QbProjectLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the QbProject service. Represents a row in the &quot;t_qb_project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QbProjectImpl}.
 * </p>
 *
 * @author 710008328
 * @see QbProjectImpl
 * @see com.genpact.model.QbProject
 * @generated
 */
public abstract class QbProjectBaseImpl extends QbProjectModelImpl
    implements QbProject {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a qb project model instance should use the {@link QbProject} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            QbProjectLocalServiceUtil.addQbProject(this);
        } else {
            QbProjectLocalServiceUtil.updateQbProject(this);
        }
    }
}
